# config.yaml

# input and output directories
# input_dir: "/playpen-storage/levlevi/nba-positions-videos-dataset/nba-plus-statvu-dataset/game-replays"

# test dir
input_dir: "/mnt/arc/levlevi/nba-positions-videos-dataset/nba-plus-statvu-dataset/clips/707/period1"
output_dir: "/mnt/arc/levlevi/nba-positions-videos-dataset/statvu_alignment/data/results"
temp_frames_dir: "/mnt/arc/levlevi/nba-positions-videos-dataset/statvu_alignment/data/temp"

# logging and device settings
log_level: "DEBUG"
time_remaining_step: 1

yolo:
  verbose: false
  roi_step: 5
  roi_conf_thresh: 0.90

yolo_model_path: "/mnt/arc/levlevi/nba-positions-videos-dataset/statvu_alignment/models/yolo/weights/tr_roi_finetune_60_large.pt"

# florence config
model_path: "/mnt/arc/levlevi/nba-positions-videos-dataset/florence_ft/model_checkpoints/muddy_garnet/epoch_1"
processor_path: "/mnt/arc/levlevi/nba-positions-videos-dataset/florence_ft/model_checkpoints/muddy_garnet/epoch_1"
use_half_precision: "True"
compile_model: "True"

# OCR settings
ocr:
  batch_size: 90
  new_max_tokens: 1028
  num_workers: 1
  num_bootstraps: 9
  do_sample: false
  early_stopping: false
  prompt: |
    1. Extract the time remaining from the on-screen clock in an NBA video frame:
    2. If visible, return time in MM:SS format with leading zeros.
    3. Return special cases:
      - Return None if no clock is visible or time can't be determined.
    Output only the time remaining:
    <time_remaining>
    [EOS]