# model and data parameters
train_annotations_fp: "/mnt/arc/levlevi/nba-positions-videos-dataset/florence_ft/data/fine-tunning-set/train.json"
val_annotations_fp: "/mnt/arc/levlevi/nba-positions-videos-dataset/florence_ft/data/fine-tunning-set/val.json"

# training parameters
num_epochs: 10
num_workers: 2
num_warmup_steps: 0
batch_size: 3
learning_rate: 1e-6